### ISSUE TITLE
Trigger lamda for calculations manually

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-backend#57]
For testing pruposes we need to run the calculations (and consequently trigger the notifications) for competitions.
Please @ricardogsilva could you report here how it can be done?

**Comment by ricardogsilva** [comment]
Competition scores are updated by a lambda function (`smbbackend.awshandlers.update_competitions`) which is setup to run periodically.

The lambda is triggered by AWS' *CloudWatch Events* service. It is currently triggered by a cron expression of the form `0 1 * * ? *` - this means the trigger is activated everyday at 01:00h.

This configuration can be inspected in the `smbbackend.zappa_settings.json` file. The [AWS web console Lambda section][lambda UI] also shows the relevant input events for the lambda.

In order to trigger it manually, one can either use [zappa][zappa] or the AWS CLI. In any case, you must specify your AWS credentials. For example, as environment variables:

```
AWS_ACCESS_KEY_ID={YOUR AWS ACCESS KEY ID}
AWS_SECRET_ACCESS_KEY={YOUR AWS SECRET ACCESS KEY}
AWS_DEFAULT_REGION="us-west-2"
```

1. With zappa - Install zappa then run the following command

   ```
   zappa invoke smbbackend 'smbbackend.awshandlers.update_competitions'
   ```

2. AWS CLI - If you do not want to use zappa, the AWS CLI may be used to invoke the lambda by running

   ```
   aws lambda invoke \
       --function-name 'savemybike-smbbackend' \
       --invocation-type Event \
       --payload '{"command": "smbbackend.awshandlers.update_competitions"}' \
       response.json
   ```

[zappa]: https://github.com/Miserlou/Zappa
[lambda UI]: https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/savemybike-smbbackend?tab=graph

**Comment by giohappy** [comment]
thanks for the clarifications @ricardogsilva

**Comment by giohappy** [comment]
@ricardogsilva how are the env vars for the lambda execution controlled by the invoker?
I mean, when the cloudwatch event triggers the lambda how and where does the execution env set up the env vars (DB, etc.) for prod or dev?

**Comment by giohappy** [comment]
As from chat, the env vars are set for each lambda version. The two current SNS topics and CloudWathch event are set to trigger specific version of the lmbda, each with their proper env vars set (dev for $LATEST version and prod for "production" alias). 
Docs with references to Lambda version is [here](https://docs.google.com/document/d/1VwFUXD_lwGW4cMWY_V7MKKfEp-eRt4n8q5XwebgZKUw/edit#heading=h.n1vwmkl9zq3q).

**Comment by ricardogsilva** [comment]
The AWS lambda code is deployed as a single lambda, but with multiple [versions][lambda version docs] and custom [aliases][lambda alias docs]. This makes use of a builtin feature of AWS, makes it easy to deploy new versions of the lambda code and rollback to a previous version in case of trouble. We are currently using the following lambda ALIASES:

-  `unqualified` - this is the default alias, which always points to the latest version, also known as `$LATEST`. This alias holds our current dev code and is used for development and testing
-  `production` - this is a custom alias which holds the version of the lambda that is being used in production.

Each alias points to a published version of the lambda code. In addition, each published version of the lambda has its own, immutable environment (the $LATEST version is a bit different, allowing the environment variables to be modified).

### Lambda publishing workflow

The workflow that I had been using is:

1. Work on the lambda code locally
2. Then use `zappa update smbbackend` in order to upload the code to AWS - Each new execution of this command pushes a new `version` to AWS and is always bound to the `$LATEST` alias
3. If some change to the dev environment is needed (i.e. if a new env variable is introduced), run the local command `set-lambda-env smbbackend` in order to update the environment of associated with the `$LATEST` alias.

And for deploying lambda code to production:

1. When code is ready to be deployed to production, use `zappa update smbbackend` as usual
2. Use a custom `zappa-production.env` file with the env vars to be used in production and load it up on the local machine with `set -o allexport; source zappa-production.env; set +o allexport`
3. Now temporarily push these env variables to AWS, thus changing the environment of the `$LATEST` alias to be the one being used in production by running `set-lambda-env smbbackend`
4. Then go to AWS console's lambda section, select the `savemybike-smbbackend` lambda and navigate to `actions -> publish new version`. This causes a new version of the lambda code to be published from the code currently in `$LATEST`. This new version also inherits all environment variables of `$LATEST`, which are now set to the production values - Take note of the version number of this newly published version (it will be used in the next step)
5. Now use the AWS console to set the `production` alias on this just published version. Do this by going to `qualifiers -> production` and then in the `ALIASES` section, select the newly published version
6. For some unknown reason, the Cloudwatch event that is being used to trigger the code that updates competitions periodically is not set up correctly, so it needs to be fixed manually. Using the AWS console, and on the `qualifiers -> production` page, access `Designer -> Cloudwatch Events`. The console should be displaying some warning that it could not match the correct rule and offer an option to fix it. Accept the option
7. Now the production code should be deployed and ready
8. Now we just need to restore the env of the `$LATEST` alias with the values used for development. Start a new local terminal, export the dev env variables locally with `set -o allexport; source dev.env; set +o allexport` and push those to AWS by running `zappa update smbbackend`

This workflow hasn't been completely automated yet (for lack of time) but it would be possible to automate it all by using the `aws cli` commands.

Additional details on this `set-lambda-env` command are present in this repo's `README` file. I'm transcribing them here for completeness:
"""
The AWS console can be used to set environment variables for each lambda function. In addition, the `smbbackend/awsutils.py` file may also be used.  It works by looking at the current local environment and searching for variables with a special naming. These vars are pushed to the lambda's environment.

This file is also installed as a console script named `set-lambda-env` when you install this package with pip.

-  Set local environment variables with the following naming convention:

   ```shell
   ZAPPA_SMBBACKEND_<VARIABLE-NAME>=<VARIABLE_VALUE>
   
   ```

-  Run the script, providing the name of the zappa stage an argument
   
Example:

For setting the `DB_HOST=somehost` env variable for the `savemybike-ingesttrack-dev` lambda, you would do the following:

```shell
export ZAPPA_SAVEMYBIKE_INGESTTRACK_DEV_DB_HOST=somehost
set-lambda-env.py smbbackend
```

Alternatively you could define all environment files in a file, then export all variables to the current environment and finally run the script
"""

[lambda version docs]: https://docs.aws.amazon.com/lambda/latest/dg/versioning-intro.html
[lambda alias docs]: https://docs.aws.amazon.com/lambda/latest/dg/aliases-intro.html
